{{- /*
based on
deployments/operator/samples/deviceplugin_v1_gpudeviceplugin.yaml
*/}}

apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: {{ .Values.name }}
  annotations: {{ toYaml .Values.annotations | nindent 4 }}
spec:
  image: "{{ .Values.image.hub }}/intel-gpu-plugin:{{ .Values.image.tag | default .Chart.AppVersion }}"
  {{- if eq .Values.initImage.enable true }}
  initImage: "{{ .Values.initImage.hub }}/intel-gpu-initcontainer:{{ .Values.initImage.tag | default .Chart.AppVersion }}"
  {{- end }}
  logLevel:  {{ .Values.logLevel }}
  sharedDevNum: {{ .Values.sharedDevNum }}
  resourceManager: {{ .Values.resourceManager }}
  enableMonitoring: {{ .Values.enableMonitoring }}
  preferredAllocationPolicy: {{ .Values.allocationPolicy }}

  nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 4 }}
---
{{ if eq .Values.nodeFeatureRule true }}
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-dp-gpu-device
spec:
  rules:
    - name: "intel.gpu"
      labels:
        "intel.feature.node.kubernetes.io/gpu": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            class: {op: In, value: ["0300", "0380"]}
        - feature: kernel.loadedmodule
          matchExpressions:
            i915: {op: Exists}
{{ end }}
