name: gpudeviceplugin-sample

image:
  hub: intel
  tag: ""

initImage:
  enable: false
  hub: intel
  tag: ""

sharedDevNum: 1
logLevel: 2
enableMonitoring: true
allocationPolicy: "none"
allowIDs: ""
denyIDs: ""
bypathMode: single

nodeSelector:
  intel.feature.node.kubernetes.io/gpu: 'true'

tolerations: []

nodeFeatureRule: true
