{{- /*
based on
deployments/operator/samples/deviceplugin_v1_dsadeviceplugin.yaml
*/}}

apiVersion: deviceplugin.intel.com/v1
kind: DsaDevicePlugin
metadata:
  name: {{ .Values.name }}
  annotations: {{ toYaml .Values.annotations | nindent 4 }}
spec:
  image: "{{ .Values.image.hub }}/intel-dsa-plugin:{{ .Values.image.tag | default .Chart.AppVersion }}"
  initImage: "{{ .Values.initImage.hub }}/intel-idxd-config-initcontainer:{{ .Values.initImage.tag | default .Chart.AppVersion }}"
  sharedDevNum: {{ .Values.sharedDevNum }}
  logLevel: {{ .Values.logLevel }}
  nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 4 }}
  tolerations: {{- .Values.tolerations | toYaml | nindent 4 }}

---
{{ if eq .Values.nodeFeatureRule true }}
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-dp-dsa-device
spec:
  rules:
    - name: "intel.dsa"
      labels:
        "intel.feature.node.kubernetes.io/dsa": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            device: {op: In, value: ["0b25"]}
            class: {op: In, value: ["0880"]}
        - feature: kernel.loadedmodule
          matchExpressions:
            idxd: {op: Exists}
{{ end }}