# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.namespace.value }}
  name: {{ .Values.configMap.AIInference.name }}
data:
{{ $v :=  .Values.configMap.AIInference.value }}
{{ (.Files.Glob $v).AsConfig | replace "restServicePort" (toString .Values.image.restfulPort) | replace "grpcServicePort" (toString .Values.image.grpcPort) | replace "maxConcurrentWorkloadPerReplica" (toString .Values.configMap.AIInference.maxConcurrentWorkloadPerReplica) | indent 2  }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.namespace.value }}
  name: {{ .Values.configMap.mediaStorage.name }}
data:
{{ $v :=  .Values.configMap.mediaStorage.value }}
{{ (.Files.Glob $v).AsConfig | replace "minIOPort_placeholder" .Values.configMap.mediaStorage.minIOPort | replace "minIOAddress_placeholder" .Values.configMap.mediaStorage.minIOAddress | replace "storageRestPort_placeholder" .Values.configMap.hbaseStorage.storageRestPort | replace "storageRestAddress_placeholder" .Values.configMap.hbaseStorage.storageRestAddress | replace "rootUserPath_placeholder" .Values.configMap.mediaStorage.rootUserMountPath | replace "rootPasswordPath_placeholder" .Values.configMap.mediaStorage.rootPasswordMountPath | indent 2  }}
