name: dsadeviceplugin-sample

image:
  hub: intel
  tag: ""

initImage:
  hub: intel
  tag: ""

sharedDevNum: 10
logLevel: 4

nodeSelector:
  intel.feature.node.kubernetes.io/dsa: 'true'

tolerations:

nodeFeatureRule: true